- name: Install dnf-pugins-core
  become: yes
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Add repo for docker
  become: yes
  command: dnf config-manager --add-repo=https://download.docker.com/linux/rhel/docker-ce.repo

- name: Modify repo for docker replace $releasever with 9
  become: yes
  replace:
      path: /etc/yum.repos.d/docker-ce.repo
      regexp: '\$releasever'
      replace: '9'

- name: Install docker
  become: yes
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Enable and start docker
  become: yes
  service:
    name: docker
    enabled: yes
    state: started

